### ISSUE TITLE
Weather fetch

### ISSUE THREAD

**Issue by sam308** [sam308/Weather-App#4]
The tag associated with the weather like "Sunny" is not being fetched from the API correctly. Please help.
The code for this lies in App.js in src folder.

**Comment by CubixPro** [comment]
Can I work on this @sam308 ?

**Comment by sam308** [comment]
Please do so!

**Comment by CubixPro** [comment]
Can you assign me this bug?

**Comment by CubixPro** [comment]
Hi can you checkout my pull request?

**Comment by sam308** [comment]
Yes, It's working! Thanks for the support!
